---
title: "ST310 coursework - NBA Career Longevity"
author: "Anastasia, Ayo and Suneet"
date: "January 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(kableExtra)
library(dplyr)
library(tree)
```

# Introduction
What we are trying to achieve

### Read in data and display the first 5 rows

```{r}
data_in <- read.csv("data_in/nba_logreg.csv")

kable(data_in[1:5,]) %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "hover", "condensed", "responsive")) %>%
  scroll_box(width = "800px")

```

### Data dictionary and description of key variables

```{r}
data_dict <- read.csv("data_in/data_dictionary.csv")

kable(data_dict) %>%
kable_styling(bootstrap_options = c("striped", "bordered", "hover", "condensed", "responsive")) %>%
  scroll_box(height = "300px")

```

# Preparing the data

### Create indicator variables

```{r}

```

# Baseline model

### A single tree classifier based on few predictors

```{r}
#only interested to classify by GP, PTS, REB, Win_Perc
features <- as.vector(c("GP", "PTS", "REB", "Win_Perc", "TARGET_5Yrs"))
tree_data <- data_in[ ,features]

fit_tree <- tree(TARGET_5Yrs ~ .,
                 data = tree_data)

plot(fit_tree, type = "uniform")
text(fit_tree, pretty = 0, cex = 1.1)

```
